Service/Areas/App/Controllers/CustomersController.cs
using Business.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Service.Areas.App.Controllers
{
    public class CustomersController : Controller
    {
        private CustomersBusiness cb;

        public CustomersController()
        {
            cb = new CustomersBusiness();
        }


        public ActionResult Index()
        {
            var customers = cb.GetCustomers();
            return View(customers);
        }

        public ActionResult Create()
        {
            return View();
        }
    }
}

Service/Areas/App/Controllers/MoviesController.cs
using Business.Business;
using Core.Model;
using Service.Areas.App.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Service.Areas.App.Controllers
{
    public class MoviesController : Controller
    {
        private MoviesBusiness mb;

        public MoviesController()
        {
            mb = new MoviesBusiness();
        }

        // GET: App/Movies
        public ActionResult Index()
        {
            var movies = mb.GetMovies();
            return View(movies);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(MovieViewModel movie)
        {
            try
            {
                Movie model = new Movie()
                {
                    Name = movie.Name,
                    Gender = movie.Gender,
                    Quantity = movie.Quantity,
                    Released = movie.Released,
                    Stats = movie.Stats,
                    ParentalGuide = movie.ParentalGuide,
                    Resume = movie.Resume
                };

                var ret = mb.AddMovie(model);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }


        public ActionResult Edit(int? id)
        {
            if (id == 0 || id == null)
            {
                return RedirectToAction("Index");
            }

            var model = mb.GetMovieById(id);

            if (model == null)
                return RedirectToAction("Index");

            MovieViewModel movie = new MovieViewModel()
            {
                ID = model.ID,
                Name = model.Name,
                Gender = model.Gender,
                Quantity = model.Quantity,
                Released = model.Released,
                Stats = model.Stats,
                ParentalGuide = model.ParentalGuide,
                Resume = model.Resume
            };

            return View(movie);
        }

        [HttpPost]
        public ActionResult Edit(MovieViewModel movie)
        {
            try
            {
                Movie model = new Movie()
                {
                    ID = movie.ID,
                    Name = movie.Name,
                    Gender = movie.Gender,
                    Quantity = movie.Quantity,
                    Released = movie.Released,
                    Stats = movie.Stats,
                    ParentalGuide = movie.ParentalGuide,
                    Resume = movie.Resume
                };

                var ret = mb.Edit(model);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        public bool Delete()
        {
            try
            {
                //bool ret = mb.Delete((int)id);
                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }
    }
}

Service/Areas/App/Controllers/RentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Service.Areas.App.Controllers
{
    public class RentsController : Controller
    {
        // GET: App/Rents
        public ActionResult Index()
        {
            return View();
        }
    }
}

Service/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Projeto Vannon</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        @Html.ActionLink("Vannon", "Index", "Home", null, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">

            <ul class="navbar-nav navbar-right justify-content-end">
                @if (User.Identity.GetUserName() != "")
                {
                    <li class="nav-item">
                        @Html.ActionLink("Alugueis", "Index", "Rents", new { area = "App" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Filmes", "Index", "Movies", new { area = "App" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Clientes", "Index", "Customers", new { area = "App" }, new { @class = "nav-link" })
                    </li>
                    @*<li class="nav-item">
                        @Html.ActionLink("Filmes","Index","Movies", new { area = "App"}, new {@class="nav-link" })
                        <a class="nav-link" href="#">Usuários</a>
                    </li>*@
                    <li class="nav-item">
                        @Html.ActionLink("Sair", "Logout", "Account", new { area = "" }, new { @class = "nav-link" })
                    </li>
                }


            </ul>

        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>